---
replicaCount: 3
image:
  repository: us.gcr.io/random-app-1533523039/random-app
  tag: 2018.0702
  pullPolicy: Always
service:
  type: NodePort
  port: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: public-ip
  path: "/"
  hosts: 
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
